import 'package:currency_exchange/common/model/currency_model.dart';

final List<CurrencyModel> currencyModels = [
  CurrencyModel(
      name: 'korea',
      countryCode: 'kr',
      currencyCode: 'KRW',
      currencySymbol: '₩',
      amount: 0.0,
      color: '#FFDDC1',
      subColor: '#FFAB91'),
  CurrencyModel(
      name: 'japan',
      countryCode: 'jp',
      currencyCode: 'JPY',
      currencySymbol: '¥',
      amount: 0.0,
      color: '#FFEBCC',
      subColor: '#FFD180'),
  CurrencyModel(
      name: 'usa',
      countryCode: 'us',
      currencyCode: 'USD',
      currencySymbol: '\$',
      amount: 0.0,
      color: '#CCE5FF',
      subColor: '#82B1FF'),
  CurrencyModel(
      name: 'eurozone',
      countryCode: 'eu',
      currencyCode: 'EUR',
      currencySymbol: '€',
      amount: 0.0,
      color: '#E6CCFF',
      subColor: '#B388FF'),
  CurrencyModel(
      name: 'china',
      countryCode: 'cn',
      currencyCode: 'CNY',
      currencySymbol: '¥',
      amount: 0.0,
      color: '#FFCCCC',
      subColor: '#FF8A80'),
  CurrencyModel(
      name: 'unitedkingdom',
      countryCode: 'gb',
      currencyCode: 'GBP',
      currencySymbol: '£',
      amount: 0.0,
      color: '#D1E7DD',
      subColor: '#A5D6A7'),
  CurrencyModel(
      name: 'switzerland',
      countryCode: 'ch',
      currencyCode: 'CHF',
      currencySymbol: 'CHF',
      amount: 0.0,
      color: '#FFF3CD',
      subColor: '#FFEB3B'),
  CurrencyModel(
      name: 'canada',
      countryCode: 'ca',
      currencyCode: 'CAD',
      currencySymbol: '\$',
      amount: 0.0,
      color: '#FFD1DC',
      subColor: '#FF80AB'),
  CurrencyModel(
      name: 'australia',
      countryCode: 'au',
      currencyCode: 'AUD',
      currencySymbol: '\$',
      amount: 0.0,
      color: '#D9EAD3',
      subColor: '#AED581'),
  CurrencyModel(
      name: 'hongkong',
      countryCode: 'hk',
      currencyCode: 'HKD',
      currencySymbol: '\$',
      amount: 0.0,
      color: '#F4CCCC',
      subColor: '#FF8A80'),
  CurrencyModel(
      name: 'singapore',
      countryCode: 'sg',
      currencyCode: 'SGD',
      currencySymbol: '\$',
      amount: 0.0,
      color: '#D9D2E9',
      subColor: '#B39DDB'),
  CurrencyModel(
      name: 'sweden',
      countryCode: 'se',
      currencyCode: 'SEK',
      currencySymbol: 'kr',
      amount: 0.0,
      color: '#FCE5CD',
      subColor: '#FFCC80'),
  CurrencyModel(
      name: 'norway',
      countryCode: 'no',
      currencyCode: 'NOK',
      currencySymbol: 'kr',
      amount: 0.0,
      color: '#D0E0E3',
      subColor: '#90CAF9'),
  CurrencyModel(
      name: 'denmark',
      countryCode: 'dk',
      currencyCode: 'DKK',
      currencySymbol: 'kr',
      amount: 0.0,
      color: '#F9CB9C',
      subColor: '#FFAB91'),
  CurrencyModel(
      name: 'india',
      countryCode: 'in',
      currencyCode: 'INR',
      currencySymbol: '₹',
      amount: 0.0,
      color: '#F6E3CE',
      subColor: '#FFCC80'),
  CurrencyModel(
      name: 'brazil',
      countryCode: 'br',
      currencyCode: 'BRL',
      currencySymbol: 'R\$',
      amount: 0.0,
      color: '#CFE2F3',
      subColor: '#90CAF9'),
  CurrencyModel(
      name: 'mexico',
      countryCode: 'mx',
      currencyCode: 'MXN',
      currencySymbol: '\$',
      amount: 0.0,
      color: '#F4CCCC',
      subColor: '#FF8A80'),
  CurrencyModel(
      name: 'russianfederation',
      countryCode: 'ru',
      currencyCode: 'RUB',
      currencySymbol: '₽',
      amount: 0.0,
      color: '#D9D2E9',
      subColor: '#B39DDB'),
  CurrencyModel(
      name: 'southafrica',
      countryCode: 'za',
      currencyCode: 'ZAR',
      currencySymbol: 'R',
      amount: 0.0,
      color: '#D9EAD3',
      subColor: '#AED581'),
  CurrencyModel(
      name: 'newzealand',
      countryCode: 'nz',
      currencyCode: 'NZD',
      currencySymbol: '\$',
      amount: 0.0,
      color: '#FFF2CC',
      subColor: '#FFEB3B'),
  CurrencyModel(
      name: 'turkey',
      countryCode: 'tr',
      currencyCode: 'TRY',
      currencySymbol: '₺',
      amount: 0.0,
      color: '#F4CCCC',
      subColor: '#FF8A80'),
  CurrencyModel(
      name: 'unitedarabemirates',
      countryCode: 'ae',
      currencyCode: 'AED',
      currencySymbol: 'د.إ',
      amount: 0.0,
      color: '#D9D2E9',
      subColor: '#B39DDB'),
  CurrencyModel(
      name: 'saudiarabia',
      countryCode: 'sa',
      currencyCode: 'SAR',
      currencySymbol: '﷼',
      amount: 0.0,
      color: '#D9EAD3',
      subColor: '#AED581'),
  CurrencyModel(
      name: 'thailand',
      countryCode: 'th',
      currencyCode: 'THB',
      currencySymbol: '฿',
      amount: 0.0,
      color: '#FFF2CC',
      subColor: '#FFEB3B'),
  CurrencyModel(
      name: 'indonesia',
      countryCode: 'id',
      currencyCode: 'IDR',
      currencySymbol: 'Rp',
      amount: 0.0,
      color: '#F4CCCC',
      subColor: '#FF8A80'),
  CurrencyModel(
      name: 'malaysia',
      countryCode: 'my',
      currencyCode: 'MYR',
      currencySymbol: 'RM',
      amount: 0.0,
      color: '#D9D2E9',
      subColor: '#B39DDB'),
  CurrencyModel(
      name: 'vietnam',
      countryCode: 'vn',
      currencyCode: 'VND',
      currencySymbol: '₫',
      amount: 0.0,
      color: '#D9EAD3',
      subColor: '#AED581'),
  CurrencyModel(
      name: 'philippines',
      countryCode: 'ph',
      currencyCode: 'PHP',
      currencySymbol: '₱',
      amount: 0.0,
      color: '#FFF2CC',
      subColor: '#FFEB3B'),
  CurrencyModel(
      name: 'israel',
      countryCode: 'il',
      currencyCode: 'ILS',
      currencySymbol: '₪',
      amount: 0.0,
      color: '#F4CCCC',
      subColor: '#FF8A80'),
  CurrencyModel(
      name: 'taiwan',
      countryCode: 'tw',
      currencyCode: 'TWD',
      currencySymbol: 'NT\$',
      amount: 0.0,
      color: '#D9D2E9',
      subColor: '#B39DDB'),
  CurrencyModel(
      name: 'chile',
      countryCode: 'cl',
      currencyCode: 'CLP',
      currencySymbol: '\$',
      amount: 0.0,
      color: '#D9EAD3',
      subColor: '#AED581'),
  CurrencyModel(
      name: 'colombia',
      countryCode: 'co',
      currencyCode: 'COP',
      currencySymbol: '\$',
      amount: 0.0,
      color: '#FFF2CC',
      subColor: '#FFEB3B'),
  CurrencyModel(
      name: 'argentina',
      countryCode: 'ar',
      currencyCode: 'ARS',
      currencySymbol: '\$',
      amount: 0.0,
      color: '#F4CCCC',
      subColor: '#FF8A80'),
  CurrencyModel(
      name: 'peru',
      countryCode: 'pe',
      currencyCode: 'PEN',
      currencySymbol: 'S/',
      amount: 0.0,
      color: '#D9D2E9',
      subColor: '#B39DDB'),
  CurrencyModel(
      name: 'czechrepublic',
      countryCode: 'cz',
      currencyCode: 'CZK',
      currencySymbol: 'Kč',
      amount: 0.0,
      color: '#D9EAD3',
      subColor: '#AED581'),
  CurrencyModel(
      name: 'hungary',
      countryCode: 'hu',
      currencyCode: 'HUF',
      currencySymbol: 'Ft',
      amount: 0.0,
      color: '#FFF2CC',
      subColor: '#FFEB3B'),
  CurrencyModel(
      name: 'poland',
      countryCode: 'pl',
      currencyCode: 'PLN',
      currencySymbol: 'zł',
      amount: 0.0,
      color: '#F4CCCC',
      subColor: '#FF8A80'),
  CurrencyModel(
      name: 'romania',
      countryCode: 'ro',
      currencyCode: 'RON',
      currencySymbol: 'lei',
      amount: 0.0,
      color: '#D9D2E9',
      subColor: '#B39DDB'),
  CurrencyModel(
      name: 'bulgaria',
      countryCode: 'bg',
      currencyCode: 'BGN',
      currencySymbol: 'лв',
      amount: 0.0,
      color: '#D9EAD3',
      subColor: '#AED581'),
  CurrencyModel(
      name: 'qatar',
      countryCode: 'qa',
      currencyCode: 'QAR',
      currencySymbol: '﷼',
      amount: 0.0,
      color: '#FFF2CC',
      subColor: '#FFEB3B'),
  CurrencyModel(
      name: 'kuwait',
      countryCode: 'kw',
      currencyCode: 'KWD',
      currencySymbol: 'د.ك',
      amount: 0.0,
      color: '#F4CCCC',
      subColor: '#FF8A80'),
  CurrencyModel(
      name: 'oman',
      countryCode: 'om',
      currencyCode: 'OMR',
      currencySymbol: '﷼',
      amount: 0.0,
      color: '#D9D2E9',
      subColor: '#B39DDB'),
  CurrencyModel(
      name: 'egypt',
      countryCode: 'eg',
      currencyCode: 'EGP',
      currencySymbol: '£',
      amount: 0.0,
      color: '#D9EAD3',
      subColor: '#AED581'),
  CurrencyModel(
      name: 'pakistan',
      countryCode: 'pk',
      currencyCode: 'PKR',
      currencySymbol: '₨',
      amount: 0.0,
      color: '#FFF2CC',
      subColor: '#FFEB3B'),
  CurrencyModel(
      name: 'srilanka',
      countryCode: 'lk',
      currencyCode: 'LKR',
      currencySymbol: '₨',
      amount: 0.0,
      color: '#F4CCCC',
      subColor: '#FF8A80'),
  CurrencyModel(
      name: 'bangladesh',
      countryCode: 'bd',
      currencyCode: 'BDT',
      currencySymbol: '৳',
      amount: 0.0,
      color: '#D9D2E9',
      subColor: '#B39DDB'),
  CurrencyModel(
      name: 'nigeria',
      countryCode: 'ng',
      currencyCode: 'NGN',
      currencySymbol: '₦',
      amount: 0.0,
      color: '#D9EAD3',
      subColor: '#AED581'),
  CurrencyModel(
      name: 'morocco',
      countryCode: 'ma',
      currencyCode: 'MAD',
      currencySymbol: 'د.م.',
      amount: 0.0,
      color: '#FFF2CC',
      subColor: '#FFEB3B'),
  CurrencyModel(
      name: 'kazakhstan',
      countryCode: 'kz',
      currencyCode: 'KZT',
      currencySymbol: '₸',
      amount: 0.0,
      color: '#F4CCCC',
      subColor: '#FF8A80'),
];
